FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y haproxy && rm -rf /var/lib/apt/lists/*

COPY ./docker/balancer/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
